### PR TITLE
Allow use of zend-stdlib v3.x

### PR DESCRIPTION
**Pull request by yukoff**

### CODE REVIEW

**Comment by solverat** [comment]
@weierophinney please could you take a look on this? thanks! 👍

**Comment by weierophinney** [comment]
This component has not been maintained since we split it from the ZF1 sources; we have no plans to make any further releases.

**Comment by solverat** [comment]
ok, thanks for your time!

**Comment by Xerkus** [comment]
Closing PR as component is not maintained

**Pull request closed without merging**
